################################################################################
# Project: odroid-xen-rtos
# 
# Module: lib
# 
# Author: Ivan Pavic (@dumpram)
#
# version: 0.0.0
################################################################################

all:
	+$(MAKE) -C FreeRTOS

clean:
	+$(MAKE) -C FreeRTOS clean
