################################################################################
# Project: odroid-xen-rtos
# 
# Module: arch
# 
# Author: Ivan Pavic (@dumpram)
#
# version: 0.0.0
################################################################################

all:
	+$(MAKE) -C arm
	+$(MAKE) -C xen

clean:
	+$(MAKE) -C arm clean
	+$(MAKE) -C xen clean
